FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*
COPY ./Reactjs/ /usr/share/nginx/html/

# Run env injection script at container startup (nginx entrypoint)
COPY ./99-env.sh /docker-entrypoint.d/99-env.sh
RUN sed -i 's/\r$//' /docker-entrypoint.d/99-env.sh && chmod +x /docker-entrypoint.d/99-env.sh

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
