export const LOCAL_PLACES = [
    {
        id: 1,
        name: "Aeon Mall Bình Tân",
        type: "another",
        address: "1 Đường Số 17A, Bình Trị Đông B, Bình Tân, TP.HCM",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7441,
        lng: 106.6117,
        temp: "31°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=500",
        desc: "Trung tâm mua sắm và giải trí sầm uất tại khu vực phía Tây thành phố."
    },
    {
        id: 2,
        name: "Aeon Mall Tân Phú",
        type: "another",
        address: "30 Bờ Bao Tân Thắng, Sơn Kỳ, Tân Phú, TP.HCM",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8016,
        lng: 106.6163,
        temp: "31°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1567449303078-57ad995bd301?w=500",
        desc: "Trung tâm thương mại Aeon đầu tiên tại Việt Nam với không gian rộng lớn."
    },
    {
        id: 3,
        name: "Bảo tàng Áo Dài",
        type: "sight",
        address: "206/19/30 Đường Long Thuận, Long Phước, Quận 9",
        price: "100.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8142,
        lng: 106.8450,
        temp: "30°C",
        weatherIcon: "fa-cloud-sun",
        img: "https://images.unsplash.com/photo-1610450535313-0570b599307b?w=500",
        desc: "Nơi tôn vinh và lưu giữ vẻ đẹp của quốc phục Việt Nam qua các thời kỳ."
    },
    {
        id: 4,
        name: "Bảo tàng Chiến dịch Hồ Chí Minh",
        type: "sight",
        address: "2 Lê Duẩn, Bến Nghé, Quận 1, TP.HCM",
        price: "30.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7836,
        lng: 106.7025,
        temp: "32°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=500",
        desc: "Lưu giữ những hiện vật quan trọng trong chiến dịch giải phóng miền Nam."
    },
    {
        id: 5,
        name: "Bảo tàng Chứng tích Chiến tranh",
        type: "sight",
        address: "28 Võ Văn Tần, Phường 6, Quận 3, TP.HCM",
        price: "40.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7795,
        lng: 106.6921,
        temp: "32°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1623940134448-f686c1264c8d?w=500",
        desc: "Bảo tàng chuyên đề nghiên cứu về hậu quả của cuộc chiến tranh xâm lược."
    },
    {
        id: 6,
        name: "Bảo tàng Địa chất",
        type: "sight",
        address: "2 Nguyễn Bỉnh Khiêm, Bến Nghé, Quận 1, TP.HCM",
        price: "20.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7876,
        lng: 106.7049,
        temp: "32°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500",
        desc: "Trưng bày các mẫu đá quý, khoáng sản và hóa thạch quý hiếm tại Việt Nam."
    },
    {
        id: 7,
        name: "Bảo tàng Lịch sử TP.HCM",
        type: "sight",
        address: "2 Nguyễn Bỉnh Khiêm, Bến Nghé, Quận 1, TP.HCM",
        price: "30.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7874,
        lng: 106.7053,
        temp: "32°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=500",
        desc: "Nơi trưng bày các di sản văn hóa Việt Nam từ thời cổ đại đến nay."
    },
    {
        id: 8,
        name: "Bảo tàng Lực lượng Vũ trang Miền Đông",
        type: "sight",
        address: "247 Hoàng Văn Thụ, Phường 1, Tân Bình, TP.HCM",
        price: "20.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7997,
        lng: 106.6669,
        temp: "31°C",
        weatherIcon: "fa-cloud-sun",
        img: "https://images.unsplash.com/photo-1576402187878-974f70c890a5?w=500",
        desc: "Trưng bày vũ khí và lịch sử quân sự của quân và dân miền Đông Nam Bộ."
    },
    {
        id: 9,
        name: "Bảo tàng Mỹ thuật TP.HCM",
        type: "sight",
        address: "97A Phó Đức Chính, Nguyễn Thái Bình, Quận 1",
        price: "30.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7699,
        lng: 106.6991,
        temp: "31°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1518998053574-53f1f61f9b86?w=500",
        desc: "Tòa kiến trúc Pháp cổ kính trưng bày các tác phẩm hội họa, điêu khắc đặc sắc."
    },
    {
        id: 10,
        name: "Bảo tàng Phụ nữ Nam Bộ",
        type: "sight",
        address: "202 Võ Thị Sáu, Phường 7, Quận 3, TP.HCM",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7845,
        lng: 106.6872,
        temp: "32°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1621609764095-b32bbe35cf3a?w=500",
        desc: "Nơi lưu giữ giá trị lịch sử, văn hóa của phụ nữ miền Nam trong kháng chiến."
    },
    {
        id: 11,
        name: "Bến Nhà Rồng",
        type: "sight",
        address: "01 Nguyễn Tất Thành, Phường 12, Quận 4, TP.HCM",
        price: "20.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7683,
        lng: 106.7067,
        temp: "31°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=500",
        desc: "Nơi Bác Hồ ra đi tìm đường cứu nước, di tích lịch sử quan trọng của cả nước."
    },
    {
        id: 12,
        name: "Blank Lounge Landmark 81",
        type: "cafe",
        address: "Tầng 75-76, Landmark 81, Quận Bình Thạnh",
        price: "150.000đ - 500.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7950,
        lng: 106.7218,
        temp: "29°C",
        weatherIcon: "fa-moon",
        img: "https://images.unsplash.com/photo-1559300589-3286596b010b?w=500",
        desc: "Lounge bar cao nhất Đông Nam Á với tầm nhìn toàn cảnh Sài Gòn rực rỡ."
    },
    {
        id: 13,
        name: "Bưu điện Trung tâm Sài Gòn",
        type: "sight",
        address: "2 Công xã Paris, Bến Nghé, Quận 1, TP.HCM",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7798,
        lng: 106.6999,
        temp: "32°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1594411130634-118809983424?w=500",
        desc: "Kiến trúc Pháp cổ điển biểu tượng của Sài Gòn, điểm check-in không thể bỏ qua."
    },
    {
        id: 14,
        name: "Cà phê Du Miên",
        type: "cafe",
        address: "7 Phan Văn Trị, Phường 10, Gò Vấp, TP.HCM",
        price: "50.000đ - 100.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8273,
        lng: 106.6775,
        temp: "32°C",
        weatherIcon: "fa-leaf",
        img: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=500",
        desc: "Quán cà phê sân vườn nổi tiếng với những ngôi nhà trên cây độc đáo và thác nước."
    },
    {
        id: 15,
        name: "Cánh đồng diều Quận 2",
        type: "another",
        address: "Đường R12, Phường An Khánh, Quận 2 (Thủ Đức)",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7812,
        lng: 106.7185,
        temp: "30°C",
        weatherIcon: "fa-wind",
        img: "https://images.unsplash.com/photo-1551009175-8a68da93d5f9?w=500",
        desc: "Khoảng không xanh mát lý tưởng để ngắm hoàng hôn và thả diều cuối tuần."
    },
    {
        id: 16,
        name: "Cầu Ánh Sao",
        type: "sight",
        address: "Khu đô thị Phú Mỹ Hưng, Quận 7, TP.HCM",
        price: "Miễn phí",
        status: "Mở đèn buổi tối",
        isOpen: true,
        lat: 10.7291,
        lng: 106.7194,
        temp: "29°C",
        weatherIcon: "fa-star",
        img: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=500",
        desc: "Cây cầu đi bộ lãng mạn nhất Sài Gòn với hệ thống đèn led đổi màu và thác nước."
    },
    {
        id: 17,
        name: "Cầu Ba Son",
        type: "sight",
        address: "Nối Quận 1 và Thành phố Thủ Đức",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7766,
        lng: 106.7118,
        temp: "31°C",
        weatherIcon: "fa-wind",
        img: "https://images.unsplash.com/photo-1555930058-2976696b010b?w=500",
        desc: "Cây cầu dây văng hiện đại - biểu tượng mới kiến trúc của TP.HCM."
    },
    {
        id: 18,
        name: "Cầu Mống",
        type: "sight",
        address: "Nối liền Quận 1 và Quận 4, bắc qua kênh Bến Nghé",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7687,
        lng: 106.7042,
        temp: "31°C",
        weatherIcon: "fa-cloud-sun",
        img: "https://images.unsplash.com/photo-1589519160158-1d2a33ec437e?w=500",
        desc: "Một trong những cây cầu cổ nhất Sài Gòn với màu xanh bạc hà đặc trưng."
    },
    {
        id: 19,
        name: "Chill Skybar",
        type: "nightlife",
        address: "Tầng 26, AB Tower, 76A Lê Lai, Quận 1",
        price: "200.000đ - 1.000.000đ",
        status: "Mở cửa tối",
        isOpen: true,
        lat: 10.7718,
        lng: 106.6946,
        temp: "28°C",
        weatherIcon: "fa-glass-cheers",
        img: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=500",
        desc: "Rooftop bar nổi tiếng hàng đầu Sài Gòn với âm nhạc sôi động và view Q1."
    },
    {
        id: 20,
        name: "Chợ Bến Thành",
        type: "sight",
        address: "Đường Lê Lợi, Bến Thành, Quận 1, TP.HCM",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7725,
        lng: 106.6980,
        temp: "32°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1571401835393-8c5f35328320?w=500",
        desc: "Biểu tượng giao thương lâu đời và nhộn nhịp nhất giữa lòng TP. Hồ Chí Minh."
    },
    {
        id: 21,
        name: "Chợ Bình Tây (Chợ Lớn)",
        type: "sight",
        address: "57A Tháp Mười, Phường 2, Quận 6",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7497,
        lng: 106.6525,
        temp: "31°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1559592442-6e680bc19660?w=500",
        desc: "Khu chợ sỉ lớn nhất và lâu đời nhất của cộng đồng người Hoa tại Sài Gòn."
    },
    {
        id: 22,
        name: "Chợ Đêm Hạnh Thông Tây",
        type: "another",
        address: "Quang Trung, Phường 11, Quận Gò Vấp",
        price: "Miễn phí",
        status: "Mở cửa tối",
        isOpen: true,
        lat: 10.8353,
        lng: 106.6662,
        temp: "29°C",
        weatherIcon: "fa-moon",
        img: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=500",
        desc: "Thiên đường mua sắm quần áo giá rẻ nhộn nhịp nhất về đêm tại Gò Vấp."
    },
    {
        id: 23,
        name: "Chợ Hoa Hồ Thị Kỷ",
        type: "food",
        address: "Hẻm 52 Hồ Thị Kỷ, Phường 1, Quận 10",
        price: "Miễn phí",
        status: "Mở cửa 24/7",
        isOpen: true,
        lat: 10.7656,
        lng: 106.6782,
        temp: "30°C",
        weatherIcon: "fa-leaf",
        img: "https://images.unsplash.com/photo-1590595978583-39b7cf302044?w=500",
        desc: "Chợ hoa đầu mối lớn nhất thành phố và là thiên đường ẩm thực đường phố nổi tiếng."
    },
    {
        id: 24,
        name: "Chùa Ấn Giáo Mariamman",
        type: "sight",
        address: "45 Trương Định, Phường Bến Thành, Quận 1",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7729,
        lng: 106.6957,
        temp: "31°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1548013146-72479768bbaa?w=500",
        desc: "Ngôi chùa Ấn Độ giáo rực rỡ với kiến trúc đặc trưng giữa trung tâm Quận 1."
    },
    {
        id: 25,
        name: "Chùa Bà Thiên Hậu",
        type: "sight",
        address: "710 Nguyễn Trãi, Phường 11, Quận 5",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7523,
        lng: 106.6610,
        temp: "31°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1528127269322-539801943592?w=500",
        desc: "Ngôi chùa cổ nhất của người Hoa, nổi tiếng với những vòng nhang treo lơ lửng."
    },
    {
        id: 26,
        name: "Chùa Bửu Long",
        type: "sight",
        address: "81 Nguyễn Xiển, Long Bình, TP. Thủ Đức",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8710,
        lng: 106.8335,
        temp: "30°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1622760814921-6677f54b6691?w=500",
        desc: "Được mệnh danh là 'chùa Thái Lan', lọt top 10 ngôi chùa đẹp nhất thế giới."
    },
    {
        id: 27,
        name: "Chùa Giác Lâm",
        type: "sight",
        address: "565 Lạc Long Quân, Phường 10, Quận Tân Bình",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7788,
        lng: 106.6455,
        temp: "31°C",
        weatherIcon: "fa-cloud-sun",
        img: "https://images.unsplash.com/photo-1590059132231-15555c179a55?w=500",
        desc: "Ngôi chùa cổ có kiến trúc tiêu biểu của vùng đất Nam Bộ với nhiều pho tượng quý."
    },
    {
        id: 28,
        name: "Chùa Ngọc Hoàng (Phước Hải Tự)",
        type: "sight",
        address: "73 Mai Thị Lựu, Đa Kao, Quận 1",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7918,
        lng: 106.6983,
        temp: "32°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1621252179027-94459d278660?w=500",
        desc: "Ngôi chùa linh thiêng từng được Tổng thống Obama ghé thăm năm 2016."
    },
    {
        id: 29,
        name: "Chùa Vĩnh Nghiêm",
        type: "sight",
        address: "339 Nam Kỳ Khởi Nghĩa, Phường 7, Quận 3",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7876,
        lng: 106.6826,
        temp: "32°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1616486117524-762397793d56?w=500",
        desc: "Tòa tháp đá cao nhất Việt Nam và là trung tâm Phật giáo lớn của Sài Gòn."
    },
    {
        id: 30,
        name: "Chung cư 42 Nguyễn Huệ",
        type: "cafe",
        address: "42 Nguyễn Huệ, Phường Bến Nghé, Quận 1",
        price: "Gửi xe: 10.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7742,
        lng: 106.7034,
        temp: "30°C",
        weatherIcon: "fa-coffee",
        img: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=500",
        desc: "Tòa chung cư cũ lừng danh thế giới hội tụ hàng chục quán cafe và tiệm decor phong cách."
    },
    // --- TIẾP THEO: CÔNG VIÊN VÀ CÁC ĐIỂM GIẢI TRÍ ---
    {
        id: 31,
        name: "Công viên 23 Tháng 9",
        type: "sight",
        address: "Đường Lê Lai, Phường Phạm Ngũ Lão, Quận 1",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7694,
        lng: 106.6930,
        temp: "31°C",
        weatherIcon: "fa-tree",
        img: "https://images.unsplash.com/photo-1589519160158-1d2a33ec437e?w=500",
        desc: "Lá phổi xanh ngay trung tâm thành phố, nơi thường xuyên tổ chức các lễ hội văn hóa lớn."
    },
    {
        id: 32,
        name: "Công viên Tao Đàn",
        type: "sight",
        address: "Trương Định, Phường Bến Thành, Quận 1",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7745,
        lng: 106.6917,
        temp: "31°C",
        weatherIcon: "fa-leaf",
        img: "https://images.unsplash.com/photo-1590059132231-15555c179a55?w=500",
        desc: "Công viên lâu đời nhất Sài Gòn với không gian yên tĩnh và câu lạc bộ chim cảnh buổi sáng."
    },
    {
        id: 33,
        name: "Công viên Vinhomes Central Park",
        type: "sight",
        address: "208 Nguyễn Hữu Cảnh, Phường 22, Quận Bình Thạnh",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7935,
        lng: 106.7215,
        temp: "30°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1555930058-2976696b010b?w=500",
        desc: "Công viên ven sông hiện đại lấy cảm hứng từ Central Park New York với view Landmark 81 cực đỉnh."
    },
    {
        id: 34,
        name: "Đầm Sen (Công viên văn hóa)",
        type: "sight",
        address: "3 Hòa Bình, Phường 3, Quận 11",
        price: "120.000đ - 220.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7686,
        lng: 106.6373,
        temp: "32°C",
        weatherIcon: "fa-umbrella-beach",
        img: "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=500",
        desc: "Tổ hợp giải trí lâu đời với vườn thú, thủy cung và nhiều trò chơi cảm giác mạnh."
    },
    {
        id: 35,
        name: "Địa đạo Củ Chi",
        type: "sight",
        address: "TL15, Phú Hiệp, Củ Chi, TP.HCM",
        price: "35.000đ - 70.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 11.1432,
        lng: 106.4632,
        temp: "31°C",
        weatherIcon: "fa-mountain",
        img: "https://images.unsplash.com/photo-1623940134448-f686c1264c8d?w=500",
        desc: "Hệ thống phòng thủ trong lòng đất huyền thoại, biểu tượng của ý chí quật cường Việt Nam."
    },
    {
        id: 36,
        name: "Dinh Độc Lập",
        type: "sight",
        address: "135 Nam Kỳ Khởi Nghĩa, Phường Bến Nghé, Quận 1",
        price: "65.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7770,
        lng: 106.6953,
        temp: "32°C",
        weatherIcon: "fa-university",
        img: "https://images.unsplash.com/photo-1592114714621-ccc6cacad26b?w=500",
        desc: "Di tích lịch sử quốc gia đặc biệt, nơi đánh dấu sự kiện thống nhất đất nước ngày 30/4/1975."
    },
    {
        id: 37,
        name: "Hầm Thủ Thiêm (Công viên hầm)",
        type: "sight",
        address: "Phường Thủ Thiêm, TP. Thủ Đức (Quận 2 cũ)",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7675,
        lng: 106.7082,
        temp: "29°C",
        weatherIcon: "fa-moon",
        img: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=500",
        desc: "Điểm ngắm hoàng hôn và nhìn sang Quận 1 rực rỡ nhất về đêm."
    },
    {
        id: 38,
        name: "Khu du lịch Bình Quới",
        type: "sight",
        address: "1147 Bình Quới, Phường 28, Quận Bình Thạnh",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8354,
        lng: 106.7288,
        temp: "31°C",
        weatherIcon: "fa-water",
        img: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=500",
        desc: "Không gian làng quê Nam Bộ yên bình với hàng dừa, cầu khỉ và các món ăn dân dã."
    },
    {
        id: 39,
        name: "Khu du lịch Suối Tiên",
        type: "sight",
        address: "120 Xa lộ Hà Nội, Tân Phú, TP. Thủ Đức",
        price: "120.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8613,
        lng: 106.8028,
        temp: "33°C",
        weatherIcon: "fa-dragon",
        img: "https://images.unsplash.com/photo-1567449303078-57ad995bd301?w=500",
        desc: "Công viên chủ đề văn hóa Phật giáo lớn nhất Sài Gòn với biển Tiên Đồng độc đáo."
    },
    {
        id: 40,
        name: "Khu phố Hoa (Quận 5)",
        type: "sight",
        address: "Khu vực Hải Thượng Lãn Ông - Châu Văn Liêm, Quận 5",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7512,
        lng: 106.6625,
        temp: "31°C",
        weatherIcon: "fa-temple",
        img: "https://images.unsplash.com/photo-1528127269322-539801943592?w=500",
        desc: "Nơi lưu giữ kiến trúc, ẩm thực và văn hóa đặc sắc của người Hoa tại Sài Gòn."
    },
    // --- TIẾP THEO: DANH SÁCH CHỮ C (PHẦN 2) ---
    {
        id: 41,
        name: "Chùa Hoằng Pháp",
        type: "sight",
        address: "Đường Lê Lợi, Tân Hiệp, Hóc Môn, TP.HCM",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8860,
        lng: 106.5818,
        temp: "31°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1590059132231-15555c179a55?w=500",
        desc: "Trung tâm hoằng pháp lớn, nơi thường xuyên tổ chức các khóa tu mùa hè cho hàng ngàn học sinh."
    },
    {
        id: 42,
        name: "Chùa Kỳ Quang 2",
        type: "sight",
        address: "154/4A Lê Đức Thọ, Phường 17, Quận Gò Vấp",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8465,
        lng: 106.6784,
        temp: "32°C",
        weatherIcon: "fa-cloud-sun",
        img: "https://images.unsplash.com/photo-1621252179027-94459d278660?w=500",
        desc: "Ngôi chùa độc đáo không mái, không cửa, nổi tiếng với các hoạt động thiện nguyện nuôi dạy trẻ mồ côi."
    },
    {
        id: 43,
        name: "Chùa Nam Thiên Nhất Trụ",
        type: "sight",
        address: "100 Đặng Văn Bi, Bình Thọ, TP. Thủ Đức",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8475,
        lng: 106.7645,
        temp: "31°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1528127269322-539801943592?w=500",
        desc: "Được mệnh danh là 'Chùa Một Cột' giữa lòng Sài Gòn với kiến trúc mô phỏng nguyên mẫu ở Hà Nội."
    },
    {
        id: 44,
        name: "Chùa Ông (Miếu Quan Đế)",
        type: "sight",
        address: "676 Nguyễn Trãi, Phường 11, Quận 5",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7521,
        lng: 106.6605,
        temp: "31°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1548013146-72479768bbaa?w=500",
        desc: "Di tích kiến trúc nghệ thuật cấp quốc gia với phong cách Triều Châu đặc trưng."
    },
    {
        id: 45,
        name: "Chùa Pháp Hoa",
        type: "sight",
        address: "870 Trường Sa, Phường 14, Quận 3",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7915,
        lng: 106.6798,
        temp: "30°C",
        weatherIcon: "fa-star",
        img: "https://images.unsplash.com/photo-1616486117524-762397793d56?w=500",
        desc: "Ngôi chùa lung linh soi bóng bên dòng kênh Nhiêu Lộc, đẹp nhất vào các dịp đại lễ Phật Đản."
    },
    {
        id: 46,
        name: "Chùa Vạn Phật",
        type: "sight",
        address: "66/14 Nghĩa Thục, Phường 5, Quận 5",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7538,
        lng: 106.6728,
        temp: "31°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1559592442-6e680bc19660?w=500",
        desc: "Ngôi chùa nổi tiếng với hệ thống 10.000 bức tượng Phật được bài trí khắp các tầng lầu."
    },
    {
        id: 47,
        name: "Chùa Xá Lợi",
        type: "sight",
        address: "89 Bà Huyện Thanh Quan, Võ Thị Sáu, Quận 3",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7785,
        lng: 106.6853,
        temp: "31°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1622760814921-6677f54b6691?w=500",
        desc: "Ngôi chùa mang dấu ấn lịch sử của Phật giáo Sài Gòn với tháp chuông cao nhất thành phố."
    },
    {
        id: 48,
        name: "Cô Ba Đồng Khởi",
        type: "cafe",
        address: "4-6 Đồng Khởi, Bến Nghé, Quận 1",
        price: "50.000đ - 120.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7745,
        lng: 106.7058,
        temp: "29°C",
        weatherIcon: "fa-coffee",
        img: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=500",
        desc: "Quán cafe mang đậm hơi thở Sài Gòn xưa với ban công view phố đi bộ Nguyễn Huệ cực đẹp."
    },
    {
        id: 49,
        name: "Công viên Bến Bạch Đằng",
        type: "sight",
        address: "Đường Tôn Đức Thắng, Phường Bến Nghé, Quận 1",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7735,
        lng: 106.7065,
        temp: "30°C",
        weatherIcon: "fa-wind",
        img: "https://images.unsplash.com/photo-1555930058-2976696b010b?w=500",
        desc: "Khu vực ven sông Sài Gòn vừa được cải tạo hiện đại, là điểm đi dạo và hóng mát ưa thích của giới trẻ."
    },
    {
        id: 50,
        name: "Công viên cá Koi RinRin Park",
        type: "sight",
        address: "87/8p Xuân Thới Thượng 6, Hóc Môn",
        price: "50.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8655,
        lng: 106.5785,
        temp: "32°C",
        weatherIcon: "fa-fish",
        img: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=500",
        desc: "Công viên mang phong cách Nhật Bản với hồ cá Koi quy mô lớn và vườn đá nghệ thuật."
    },
    // --- TIẾP THEO: NHÓM CÔNG VIÊN VÀ TRUNG TÂM THƯƠNG MẠI ---
    {
        id: 51,
        name: "Công viên Gia Định",
        type: "sight",
        address: "Phường 9, Quận Phú Nhuận (giáp Gò Vấp)",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8125,
        lng: 106.6788,
        temp: "31°C",
        weatherIcon: "fa-tree",
        img: "https://images.unsplash.com/photo-1590059132231-15555c179a55?w=500",
        desc: "Lá phổi xanh lớn nhất khu vực Tân Sơn Nhất với thảm cỏ rộng và nhiều cây cổ thụ."
    },
    {
        id: 52,
        name: "Công viên Hoàng Văn Thụ",
        type: "sight",
        address: "Phan Đình Giót, Phường 2, Quận Tân Bình",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8015,
        lng: 106.6665,
        temp: "31°C",
        weatherIcon: "fa-leaf",
        img: "https://images.unsplash.com/photo-1589519160158-1d2a33ec437e?w=500",
        desc: "Công viên có hình tam giác độc đáo, điểm xanh yên bình ngay cửa ngõ sân bay."
    },
    {
        id: 53,
        name: "Công viên Lê Văn Tám",
        type: "sight",
        address: "Võ Thị Sáu, Phường Đa Kao, Quận 1",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7842,
        lng: 106.6938,
        temp: "32°C",
        weatherIcon: "fa-tree",
        img: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=500",
        desc: "Không gian đi dạo và tập thể dục lý tưởng ngay trung tâm Quận 1, nổi tiếng với các lễ hội sách."
    },
    {
        id: 54,
        name: "Công viên nước Đại Thế Giới",
        type: "another",
        address: "1106 Võ Văn Kiệt, Phường 6, Quận 5",
        price: "50.000đ - 100.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7515,
        lng: 106.6732,
        temp: "32°C",
        weatherIcon: "fa-swimming-pool",
        img: "https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?w=500",
        desc: "Điểm vui chơi giải trí dưới nước lâu đời tại khu vực Quận 5 với nhiều máng trượt cảm giác mạnh."
    },
    {
        id: 55,
        name: "Công viên Tao Đàn",
        type: "sight",
        address: "55C Nguyễn Thị Minh Khai, Bến Thành, Quận 1",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7745,
        lng: 106.6917,
        temp: "31°C",
        weatherIcon: "fa-leaf",
        img: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=500",
        desc: "Khu vườn di sản giữa lòng thành phố với câu lạc bộ chim cảnh nổi tiếng mỗi sáng sớm."
    },
    {
        id: 56,
        name: "Công viên Văn hóa Đầm Sen",
        type: "sight",
        address: "03 Hòa Bình, Phường 3, Quận 11",
        price: "120.000đ - 220.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7686,
        lng: 106.6373,
        temp: "32°C",
        weatherIcon: "fa-umbrella-beach",
        img: "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=500",
        desc: "Tổ hợp giải trí lớn bậc nhất với vườn thú, thủy cung và các khu trò chơi đa dạng."
    },
    {
        id: 57,
        name: "Công viên Vinhomes Central Park",
        type: "sight",
        address: "208 Nguyễn Hữu Cảnh, Phường 22, Bình Thạnh",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7935,
        lng: 106.7215,
        temp: "30°C",
        weatherIcon: "fa-camera",
        img: "https://images.unsplash.com/photo-1555930058-2976696b010b?w=500",
        desc: "Công viên ven sông hiện đại lấy cảm hứng từ Central Park New York, view Landmark 81 cực đẹp."
    },
    {
        id: 58,
        name: "Cột cờ Thủ Ngữ",
        type: "sight",
        address: "Đường Tôn Đức Thắng, Phường Nguyễn Thái Bình, Quận 1",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7712,
        lng: 106.7065,
        temp: "30°C",
        weatherIcon: "fa-flag",
        img: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=500",
        desc: "Công trình di tích trăm tuổi cạnh sông Sài Gòn, nơi treo tín hiệu cho tàu bè ra vào cảng xưa."
    },
    {
        id: 59,
        name: "Crescent Mall",
        type: "another",
        address: "101 Tôn Dật Tiên, Tân Phú, Quận 7",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7288,
        lng: 106.7198,
        temp: "31°C",
        weatherIcon: "fa-shopping-bag",
        img: "https://images.unsplash.com/photo-1567449303078-57ad995bd301?w=500",
        desc: "Trung tâm thương mại tiêu chuẩn quốc tế nằm cạnh hồ Bán Nguyệt thơ mộng."
    },
    // --- TIẾP THEO: NHÓM CHỮ C (CẦU VÀ CÔNG TRÌNH VĂN HÓA) ---
    {
        id: 60,
        name: "Cầu Ánh Sao",
        type: "sight",
        address: "Khu đô thị Phú Mỹ Hưng, Quận 7",
        price: "Miễn phí",
        status: "Đẹp nhất buổi tối",
        isOpen: true,
        lat: 10.7274,
        lng: 106.7192,
        temp: "29°C",
        weatherIcon: "fa-star",
        img: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=500",
        desc: "Cây cầu bộ hành có hệ thống đèn LED và phun nước lung linh, biểu tượng lãng mạn của Quận 7."
    },
    {
        id: 61,
        name: "Cầu Ba Son (Cầu Thủ Thiêm 2)",
        type: "sight",
        address: "Nối Quận 1 và TP. Thủ Đức",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7781,
        lng: 106.7088,
        temp: "30°C",
        weatherIcon: "fa-bridge",
        img: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=500",
        desc: "Cây cầu dây văng hiện đại, biểu tượng mới của thành phố với view ngắm Landmark 81 cực đẹp."
    },
    {
        id: 62,
        name: "Cầu Chà Và",
        type: "sight",
        address: "Nối Quận 5 và Quận 8",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7518,
        lng: 106.6575,
        temp: "31°C",
        weatherIcon: "fa-road",
        img: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=500",
        desc: "Cây cầu cổ gắn liền với lịch sử khu vực Chợ Lớn và các hoạt động giao thương trên bến dưới thuyền."
    },
    {
        id: 63,
        name: "Cầu Mong",
        type: "sight",
        address: "Nối Quận 1 và Quận 4",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7687,
        lng: 106.7042,
        temp: "30°C",
        weatherIcon: "fa-camera",
        img: "https://images.unsplash.com/photo-1555930058-2976696b010b?w=500",
        desc: "Cây cầu bộ hành lâu đời nhất Sài Gòn với kiến trúc phương Tây, điểm check-in không thể bỏ qua."
    },
    {
        id: 64,
        name: "Cầu Phú Mỹ",
        type: "sight",
        address: "Nối Quận 7 và TP. Thủ Đức",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7585,
        lng: 106.7455,
        temp: "31°C",
        weatherIcon: "fa-bridge",
        img: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=500",
        desc: "Cây cầu dây văng lớn nhất thành phố, nơi ngắm nhìn toàn cảnh cảng biển và thành phố từ trên cao."
    },
    {
        id: 65,
        name: "Cầu Thủ Thiêm 1",
        type: "sight",
        address: "Nối Quận Bình Thạnh và TP. Thủ Đức",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7875,
        lng: 106.7155,
        temp: "30°C",
        weatherIcon: "fa-road",
        img: "https://images.unsplash.com/photo-1555930058-2976696b010b?w=500",
        desc: "Kết nối trung tâm cũ với khu đô thị mới Thủ Thiêm, điểm hóng gió quen thuộc của người dân."
    },
    {
        id: 66,
        name: "Cung Văn hóa Lao Động",
        type: "another",
        address: "55B Nguyễn Thị Minh Khai, Phường Bến Thành, Quận 1",
        price: "Theo sự kiện",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7760,
        lng: 106.6925,
        temp: "31°C",
        weatherIcon: "fa-users",
        img: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=500",
        desc: "Trung tâm sinh hoạt văn hóa, thể thao lâu đời nằm ngay cạnh công viên Tao Đàn."
    },
    {
        id: 67,
        name: "Cửa hàng xăng đơn (Số 1)",
        type: "another",
        address: "Khu vực trung tâm Quận 1",
        price: "Theo giá thị trường",
        status: "24/7",
        isOpen: true,
        lat: 10.7715,
        lng: 106.6985,
        temp: "31°C",
        weatherIcon: "fa-gas-pump",
        img: "https://images.unsplash.com/photo-1545147986-a9d6f210df77?w=500",
        desc: "Trạm cung cấp nhiên liệu thuận tiện cho các lộ trình di chuyển trong nội đô."
    },
    {
        id: 68,
        name: "Cơm Tấm Ba Ghiền",
        type: "food",
        address: "84 Đặng Văn Ngữ, Phường 10, Phú Nhuận",
        price: "70.000đ - 150.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7944,
        lng: 106.6695,
        temp: "32°C",
        weatherIcon: "fa-utensils",
        img: "https://images.unsplash.com/photo-1567449303078-57ad995bd301?w=500",
        desc: "Quán cơm tấm huyền thoại với miếng sườn khổng lồ, nổi tiếng nhất Sài Gòn."
    },
    {
        id: 69,
        name: "Cơm Tấm Kiều Giang",
        type: "food",
        address: "192 Trần Quang Khải, Tân Định, Quận 1",
        price: "50.000đ - 100.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7915,
        lng: 106.6892,
        temp: "31°C",
        weatherIcon: "fa-utensils",
        img: "https://images.unsplash.com/photo-1589519160158-1d2a33ec437e?w=500",
        desc: "Chuỗi cơm tấm lâu đời với hương vị truyền thống và không gian phục vụ chuyên nghiệp."
    },
    // --- TIẾP THEO: NHÓM CHỮ C (CÒN LẠI) VÀ CHỮ D ---
    {
        id: 70,
        name: "Cửa hàng xăng dầu số 1 (Petrolimex)",
        type: "another",
        address: "136 Hai Bà Trưng, Đa Kao, Quận 1",
        price: "Theo giá thị trường",
        status: "Mở cửa 24/7",
        isOpen: true,
        lat: 10.7832,
        lng: 106.6955,
        temp: "31°C",
        weatherIcon: "fa-gas-pump",
        img: "https://images.unsplash.com/photo-1545147986-a9d6f210df77?w=500",
        desc: "Trạm xăng trung tâm, tiện lợi cho việc nạp nhiên liệu khi di chuyển qua các quận nội thành."
    },
    {
        id: 71,
        name: "Đá Bào Concept",
        type: "cafe",
        address: "18 Tú Xương, Võ Thị Sáu, Quận 3",
        price: "60.000đ - 150.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7818,
        lng: 106.6875,
        temp: "30°C",
        weatherIcon: "fa-mug-hot",
        img: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=500",
        desc: "Quán cafe mang phong cách kiến trúc cổ điển pha lẫn hiện đại, không gian cực kỳ nghệ thuật."
    },
    {
        id: 72,
        name: "Đầm Sen Tam Đa",
        type: "sight",
        address: "361/20 Tam Đa, Trường Thạnh, Quận 9",
        price: "30.000đ - 50.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8125,
        lng: 106.8455,
        temp: "31°C",
        weatherIcon: "fa-leaf",
        img: "https://images.unsplash.com/photo-1590595978583-39b7cf302044?w=500",
        desc: "Vườn sen rộng lớn ngoại ô thành phố, điểm check-in lý tưởng với khung cảnh làng quê yên bình."
    },
    {
        id: 73,
        name: "Đảo Khỉ Cần Giờ",
        type: "sight",
        address: "Long Hòa, Cần Giờ, TP.HCM",
        price: "35.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.4855,
        lng: 106.8745,
        temp: "30°C",
        weatherIcon: "fa-paw",
        img: "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=500",
        desc: "Khu bảo tồn thiên nhiên với hàng ngàn chú khỉ tự nhiên, trải nghiệm đi cano xuyên rừng ngập mặn."
    },
    {
        id: 74,
        name: "Đền Hùng Quận 9 (Công viên Lịch sử Văn hóa Dân tộc)",
        type: "sight",
        address: "Đường số 16, Long Bình, TP. Thủ Đức",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8795,
        lng: 106.8285,
        temp: "31°C",
        weatherIcon: "fa-landmark",
        img: "https://images.unsplash.com/photo-1621252179027-94459d278660?w=500",
        desc: "Công trình tưởng niệm các vua Hùng uy nghi với kiến trúc truyền thống trên đồi cao."
    },
    {
        id: 75,
        name: "Địa đạo Bến Dược",
        type: "sight",
        address: "Phú Hiệp, Củ Chi, TP.HCM",
        price: "35.000đ - 70.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 11.1435,
        lng: 106.4635,
        temp: "31°C",
        weatherIcon: "fa-mountain",
        img: "https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=500",
        desc: "Hệ thống địa đạo quy mô lớn nhất Củ Chi, nơi lưu giữ những trang sử hào hùng dưới lòng đất."
    },
    {
        id: 76,
        name: "Diamond Plaza",
        type: "another",
        address: "34 Lê Duẩn, Bến Nghé, Quận 1",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7795,
        lng: 106.6995,
        temp: "32°C",
        weatherIcon: "fa-shopping-cart",
        img: "https://images.unsplash.com/photo-1567449303078-57ad995bd301?w=500",
        desc: "Trung tâm thương mại cao cấp đầu tiên tại TP.HCM, nằm ngay cạnh Nhà thờ Đức Bà."
    },
    {
        id: 77,
        name: "Dinh thự Phương Nam",
        type: "sight",
        address: "Khu vực Quận 1 / Thủ Đức (Gợi ý tham quan kiến trúc)",
        price: "Theo sự kiện",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7755,
        lng: 106.7025,
        temp: "31°C",
        weatherIcon: "fa-home",
        img: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500",
        desc: "Tòa kiến trúc mang đậm dấu ấn lịch sử với phong cách cổ điển sang trọng."
    },
    {
        id: 78,
        name: "Dinh Thượng Thơ",
        type: "sight",
        address: "59-61 Lý Tự Trọng, Bến Nghé, Quận 1",
        price: "Tham quan bên ngoài",
        status: "Kiến trúc di tích",
        isOpen: true,
        lat: 10.7765,
        lng: 106.6992,
        temp: "31°C",
        weatherIcon: "fa-archway",
        img: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=500",
        desc: "Một trong những tòa nhà cổ nhất Sài Gòn (1864) với vẻ đẹp kiến trúc Pháp còn vẹn nguyên."
    },
    {
        id: 79,
        name: "Đường Sách TP.HCM",
        type: "sight",
        address: "Đường Nguyễn Văn Bình, Bến Nghé, Quận 1",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7802,
        lng: 106.6995,
        temp: "31°C",
        weatherIcon: "fa-book-open",
        img: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500",
        desc: "Không gian văn hóa đọc nổi tiếng nhất thành phố, yên bình và đậm chất nghệ thuật."
    },
    // --- TIẾP THEO: NHÓM ĐỊA ĐIỂM CHỮ E, G, H, K ---
    {
        id: 80,
        name: "Emart Gò Vấp",
        type: "another",
        address: "366 Phan Văn Trị, Phường 5, Quận Gò Vấp",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8275,
        lng: 106.6915,
        temp: "32°C",
        weatherIcon: "fa-shopping-cart",
        img: "https://images.unsplash.com/photo-1534452203293-494d7ddbf7e0?w=500",
        desc: "Đại siêu thị nổi tiếng với bức tường check-in huyền thoại và khu ẩm thực Hàn Quốc giá rẻ."
    },
    {
        id: 81,
        name: "Estella Place",
        type: "another",
        address: "88 Song Hành, An Phú, Quận 2 (TP. Thủ Đức)",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8018,
        lng: 106.7415,
        temp: "31°C",
        weatherIcon: "fa-store",
        img: "https://images.unsplash.com/photo-1567449303078-57ad995bd301?w=500",
        desc: "Trung tâm thương mại kiểu mẫu với không gian xanh mát và nhiều khu vui chơi cho trẻ em."
    },
    {
        id: 82,
        name: "Gigamall Thủ Đức",
        type: "another",
        address: "240-242 Phạm Văn Đồng, Hiệp Bình Chánh, TP. Thủ Đức",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8272,
        lng: 106.7212,
        temp: "31°C",
        weatherIcon: "fa-lightbulb",
        img: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=500",
        desc: "Trung tâm thương mại công nghệ với khu giải trí tương tác JP World hiện đại."
    },
    {
        id: 83,
        name: "Hẻm Bia Lost in HongKong",
        type: "nightlife",
        address: "175/19 Phạm Ngũ Lão, Quận 1",
        price: "50.000đ - 200.000đ",
        status: "Mở cửa tối",
        isOpen: true,
        lat: 10.7672,
        lng: 106.6935,
        temp: "28°C",
        weatherIcon: "fa-glass-cheers",
        img: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=500",
        desc: "Con hẻm mang phong cách Hong Kong thập niên 90 rực rỡ ánh đèn neon, điểm nhậu cực chill của giới trẻ."
    },
    {
        id: 84,
        name: "Hồ Bán Nguyệt",
        type: "sight",
        address: "Khu đô thị Phú Mỹ Hưng, Quận 7",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7285,
        lng: 106.7195,
        temp: "29°C",
        weatherIcon: "fa-water",
        img: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=500",
        desc: "Cung đường đi bộ ven hồ thơ mộng, nơi diễn ra hội hoa xuân và các sự kiện countdown hoành tráng."
    },
    {
        id: 85,
        name: "Hồ Con Rùa",
        type: "sight",
        address: "Công trường Quốc Tế, Quận 3",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7825,
        lng: 106.6962,
        temp: "30°C",
        weatherIcon: "fa-utensils",
        img: "https://images.unsplash.com/photo-1555930058-2976696b010b?w=500",
        desc: "Vòng xoay mang tính biểu tượng, thiên đường ăn vặt và điểm tụ tập quen thuộc mỗi tối của sinh viên."
    },
    {
        id: 86,
        name: "Khu dã ngoại Green Park",
        type: "sight",
        address: "Củ Chi / Quận 12 (Khu vực ven sông)",
        price: "50.000đ - 100.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8855,
        lng: 106.6425,
        temp: "31°C",
        weatherIcon: "fa-campground",
        img: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=500",
        desc: "Không gian xanh lý tưởng cho các hoạt động team building và cắm trại cuối tuần gần thành phố."
    },
    {
        id: 87,
        name: "Khu du lịch Văn Thánh",
        type: "sight",
        address: "48/10 Điện Biên Phủ, Phường 22, Bình Thạnh",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7995,
        lng: 106.7125,
        temp: "31°C",
        weatherIcon: "fa-leaf",
        img: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=500",
        desc: "Ốc đảo xanh giữa lòng phố thị với kiến trúc nhà sàn, ao sen đậm chất làng quê Việt Nam."
    },
    // --- TIẾP THEO: NHÓM KHU DU LỊCH VÀ LANDMARK ---
    {
        id: 88,
        name: "Khu du lịch sinh thái Vàm Sát",
        type: "sight",
        address: "Lý Nhơn, Cần Giờ, TP.HCM",
        price: "35.000đ - 100.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.4572,
        lng: 106.8855,
        temp: "30°C",
        weatherIcon: "fa-leaf",
        img: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=500",
        desc: "Khu dự trữ sinh quyển thế giới với hệ sinh thái rừng ngập mặn đa dạng và Đầm Dơi tự nhiên."
    },
    {
        id: 89,
        name: "Khu du lịch The BCR",
        type: "another",
        address: "191 Tam Đa, Trường Thạnh, Quận 9",
        price: "50.000đ - 200.000đ",
        status: "Thường đông vào cuối tuần",
        isOpen: true,
        lat: 10.8115,
        lng: 106.8442,
        temp: "31°C",
        weatherIcon: "fa-swimming-pool",
        img: "https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?w=500",
        desc: "Khu vui chơi giải trí ngoài trời nổi tiếng với hồ bơi vô cực sát sông và các trò chơi bắn súng sơn."
    },
    {
        id: 90,
        name: "Khu thả diều Hóc Môn",
        type: "another",
        address: "Đặng Thúc Vịnh, Thới Tam Thôn, Hóc Môn",
        price: "Miễn phí",
        status: "Nhộn nhịp buổi chiều",
        isOpen: true,
        lat: 10.8812,
        lng: 106.6085,
        temp: "30°C",
        weatherIcon: "fa-wind",
        img: "https://images.unsplash.com/photo-1551009175-8a68da93d5f9?w=500",
        desc: "Bãi thả diều rộng lớn, điểm tụ tập hóng mát và vui chơi bình dân của người dân ngoại ô."
    },
    {
        id: 91,
        name: "L'Usine Le Loi",
        type: "cafe",
        address: "70 Lê Lợi, Phường Bến Thành, Quận 1",
        price: "60.000đ - 200.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7738,
        lng: 106.6992,
        temp: "31°C",
        weatherIcon: "fa-coffee",
        img: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=500",
        desc: "Concept store nổi tiếng kết hợp giữa cafe mang phong cách Pháp và cửa hàng thời trang thiết kế."
    },
    {
        id: 92,
        name: "Landmark 81",
        type: "sight",
        address: "720A Điện Biên Phủ, Phường 22, Bình Thạnh",
        price: "Miễn phí tham quan sảnh",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7950,
        lng: 106.7218,
        temp: "29°C",
        weatherIcon: "fa-building",
        img: "https://images.unsplash.com/photo-1555930058-2976696b010b?w=500",
        desc: "Tòa nhà cao nhất Việt Nam, biểu tượng mới của sự thịnh vượng với đài quan sát Skyview tuyệt đẹp."
    },
    {
        id: 93,
        name: "Làng du lịch Tre Việt",
        type: "sight",
        address: "25 Phan Văn Đáng, Phú Hữu, Nhơn Trạch (Giáp Quận 2)",
        price: "50.000đ - 150.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7655,
        lng: 106.7915,
        temp: "31°C",
        weatherIcon: "fa-water",
        img: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=500",
        desc: "Khu nghỉ dưỡng đậm chất sông nước với các trò chơi dân gian và ẩm thực buffet đồng quê."
    },
    // --- TIẾP THEO: NHÓM LĂNG ÔNG, MIẾU NỔI VÀ NHÀ THỜ ---
    {
        id: 94,
        name: "Lăng Lê Văn Duyệt (Lăng Ông Bà Chiểu)",
        type: "sight",
        address: "01 Vũ Tùng, Phường 1, Quận Bình Thạnh",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8012,
        lng: 106.6985,
        temp: "31°C",
        weatherIcon: "fa-place-of-worship",
        img: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=500",
        desc: "Khu lăng mộ của Tả quân Lê Văn Duyệt với kiến trúc cổ điển, là biểu tượng tâm linh của vùng đất Gia Định xưa."
    },
    {
        id: 95,
        name: "Little Japan Town",
        type: "food",
        address: "8A Lê Thánh Tôn, Bến Nghé, Quận 1",
        price: "100.000đ - 500.000đ",
        status: "Nhộn nhịp nhất buổi tối",
        isOpen: true,
        lat: 10.7792,
        lng: 106.7042,
        temp: "29°C",
        weatherIcon: "fa-utensils",
        img: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=500",
        desc: "Khu phố Nhật giữa lòng Sài Gòn với những con hẻm nhỏ đầy quán ramen, sushi và không gian check-in như tại Tokyo."
    },
    {
        id: 96,
        name: "Miếu Nổi Gò Vấp (Phù Châu Miếu)",
        type: "sight",
        address: "Trên sông Vàm Thuật, Phường 5, Gò Vấp",
        price: "Miễn phí (Phí đò: ~10k)",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8252,
        lng: 106.6995,
        temp: "31°C",
        weatherIcon: "fa-ship",
        img: "https://images.unsplash.com/photo-1528127269322-539801943592?w=500",
        desc: "Ngôi miếu hơn 300 tuổi nằm biệt lập giữa dòng sông, nổi tiếng với kiến trúc hàng ngàn con rồng bằng gốm sứ."
    },
    {
        id: 97,
        name: "Nhà hát Thành phố Hồ Chí Minh",
        type: "sight",
        address: "07 Công trường Lam Sơn, Bến Nghé, Quận 1",
        price: "Tham quan bên ngoài",
        status: "Mở cửa khi có show",
        isOpen: true,
        lat: 10.7766,
        lng: 106.7032,
        temp: "30°C",
        weatherIcon: "fa-landmark",
        img: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=500",
        desc: "Công trình kiến trúc Tây Âu tráng lệ, điểm nhấn văn hóa quan trọng ngay trung tâm thành phố."
    },
    {
        id: 98,
        name: "Nhà thờ Cha Tam",
        type: "sight",
        address: "25 Học Lạc, Phường 14, Quận 5",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7525,
        lng: 106.6545,
        temp: "31°C",
        weatherIcon: "fa-church",
        img: "https://images.unsplash.com/photo-1616486117524-762397793d56?w=500",
        desc: "Ngôi nhà thờ nổi tiếng trong khu phố Hoa với sự kết hợp kiến trúc Gothique và trang trí kiểu Á Đông."
    },
    {
        id: 99,
        name: "Nhà thờ Chợ Quán",
        type: "sight",
        address: "120 Trần Bình Trọng, Phường 2, Quận 5",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7585,
        lng: 106.6785,
        temp: "31°C",
        weatherIcon: "fa-church",
        img: "https://images.unsplash.com/photo-1589519160158-1d2a33ec437e?w=500",
        desc: "Nhà thờ cổ nhất của Tổng giáo phận Sài Gòn với tháp chuông uy nghiêm và lịch sử lâu đời."
    },
    {
        id: 100,
        name: "Nhà thờ Đức Bà Sài Gòn",
        type: "sight",
        address: "01 Công xã Paris, Bến Nghé, Quận 1",
        price: "Miễn phí",
        status: "Đang trùng tu",
        isOpen: true, // Vẫn cho phép check-in bên ngoài
        lat: 10.7797,
        lng: 106.6990,
        temp: "32°C",
        weatherIcon: "fa-sun",
        img: "https://images.unsplash.com/photo-1594411130634-118809983424?w=500",
        desc: "Biểu tượng tôn giáo và kiến trúc Pháp của thành phố, xây dựng bằng gạch Marseille đỏ rực."
    },
    {
        id: 101,
        name: "Nhà thờ Hạnh Thông Tây",
        type: "sight",
        address: "53/7 Quang Trung, Phường 11, Gò Vấp",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8345,
        lng: 106.6668,
        temp: "31°C",
        weatherIcon: "fa-church",
        img: "https://images.unsplash.com/photo-1528127269322-539801943592?w=500",
        desc: "Công trình kiến trúc Byzantine hiếm hoi tại Sài Gòn, điểm nhấn tâm linh của khu vực Gò Vấp."
    },
    {
        id: 102,
        name: "Nhà thờ Huyện Sỹ",
        type: "sight",
        address: "1 Tôn Thất Tùng, Phạm Ngũ Lão, Quận 1",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7712,
        lng: 106.6908,
        temp: "31°C",
        weatherIcon: "fa-church",
        img: "https://images.unsplash.com/photo-1622760814921-6677f54b6691?w=500",
        desc: "Một trong những nhà thờ cổ bậc nhất thành phố, mang tên ông bà Huyện Sỹ - những người hiến đất xây dựng."
    },
    // --- TIẾP THEO: NHÀ THỜ ĐẶC SẮC, PHỐ ĐI BỘ VÀ TRUNG TÂM THÀNH PHỐ ---
    {
        id: 103,
        name: "Nhà thờ Jeanne d'Arc (Nhà thờ Ngã Sáu)",
        type: "sight",
        address: "116A Hùng Vương, Phường 9, Quận 5",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7588,
        lng: 106.6665,
        temp: "31°C",
        weatherIcon: "fa-church",
        img: "https://images.unsplash.com/photo-1548013146-72479768bbaa?w=500",
        desc: "Ngôi nhà thờ cổ nằm giữa công viên ngã sáu sầm uất, mang kiến trúc Gothique Pháp đặc trưng."
    },
    {
        id: 104,
        name: "Nhà thờ Kỳ Đồng (Dòng Chúa Cứu Thế)",
        type: "sight",
        address: "38 Kỳ Đồng, Phường 9, Quận 3",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7832,
        lng: 106.6798,
        temp: "31°C",
        weatherIcon: "fa-church",
        img: "https://images.unsplash.com/photo-1616486117524-762397793d56?w=500",
        desc: "Nhà thờ có không gian rộng lớn, hiện đại và là trung tâm hành hương quan trọng của người dân thành phố."
    },
    {
        id: 105,
        name: "Nhà thờ Tân Định (Nhà thờ Màu Hồng)",
        type: "sight",
        address: "289 Hai Bà Trưng, Võ Thị Sáu, Quận 3",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7892,
        lng: 106.6912,
        temp: "32°C",
        weatherIcon: "fa-camera",
        img: "https://images.unsplash.com/photo-1589519160158-1d2a33ec437e?w=500",
        desc: "Ngôi nhà thờ màu hồng rực rỡ thu hút hàng ngàn khách du lịch quốc tế check-in mỗi ngày."
    },
    {
        id: 106,
        name: "Nhà trưng bày tượng sáp Việt",
        type: "sight",
        address: "Cung Văn hóa Lao Động, 55B Nguyễn Thị Minh Khai, Quận 1",
        price: "50.000đ - 100.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7762,
        lng: 106.6928,
        temp: "30°C",
        weatherIcon: "fa-user-friends",
        img: "https://images.unsplash.com/photo-1518998053574-53f1f61f9b86?w=500",
        desc: "Nơi trưng bày hơn 100 bức tượng sáp các nghệ sĩ Việt Nam nổi tiếng với độ chân thực cao."
    },
    {
        id: 107,
        name: "Okkio Caffe",
        type: "cafe",
        address: "122 Lê Lợi, Phường Bến Thành, Quận 1",
        price: "60.000đ - 150.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7732,
        lng: 106.6985,
        temp: "31°C",
        weatherIcon: "fa-mug-hot",
        img: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=500",
        desc: "Quán cafe phong cách Retro nổi bật với lối vào hình xoắn ốc xanh thẳm và view nhìn ra chợ Bến Thành."
    },
    {
        id: 108,
        name: "Phố lồng đèn Lương Nhữ Học",
        type: "sight",
        address: "Đường Lương Nhữ Học, Quận 5",
        price: "Miễn phí",
        status: "Rực rỡ nhất dịp Trung Thu",
        isOpen: true,
        lat: 10.7522,
        lng: 106.6618,
        temp: "29°C",
        weatherIcon: "fa-lightbulb",
        img: "https://images.unsplash.com/photo-1590595978583-39b7cf302044?w=500",
        desc: "Con phố ngập tràn sắc màu lồng đèn thủ công, điểm đến văn hóa đặc trưng của khu Chợ Lớn."
    },
    {
        id: 109,
        name: "Phố Tây Bùi Viện",
        type: "nightlife",
        address: "Đường Bùi Viện, Phường Phạm Ngũ Lão, Quận 1",
        price: "Tùy dịch vụ",
        status: "Sầm uất nhất sau 19h",
        isOpen: true,
        lat: 10.7674,
        lng: 106.6939,
        temp: "28°C",
        weatherIcon: "fa-glass-cheers",
        img: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=500",
        desc: "Khu phố 'không ngủ' dành cho khách du lịch với vô vàn quán bar, ẩm thực đường phố và âm nhạc."
    },
    {
        id: 110,
        name: "Rừng Sác Cần Giờ",
        type: "sight",
        address: "Huyện Cần Giờ, TP.HCM",
        price: "35.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.4555,
        lng: 106.8845,
        temp: "30°C",
        weatherIcon: "fa-tree",
        img: "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=500",
        desc: "Khu căn cứ cách mạng trong rừng ngập mặn, nơi ghi dấu những chiến công anh hùng của đặc công Rừng Sác."
    },
    {
        id: 111,
        name: "Saigon Centre (Takashimaya)",
        type: "another",
        address: "65 Lê Lợi, Phường Bến Nghé, Quận 1",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7735,
        lng: 106.7012,
        temp: "31°C",
        weatherIcon: "fa-bag-shopping",
        img: "https://images.unsplash.com/photo-1567449303078-57ad995bd301?w=500",
        desc: "Trung tâm thương mại sang trọng bậc nhất Sài Gòn với các thương hiệu quốc tế và khu ẩm thực cao cấp."
    },
    {
        id: 112,
        name: "Saigon Outcast",
        type: "another",
        address: "188/1 Nguyễn Văn Hưởng, Thảo Điền, Quận 2",
        price: "Tùy sự kiện",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8062,
        lng: 106.7365,
        temp: "29°C",
        weatherIcon: "fa-palette",
        img: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=500",
        desc: "Không gian sáng tạo nghệ thuật, leo núi trong nhà và các lễ hội bia thủ công độc đáo."
    },
    {
        id: 113,
        name: "SC VivoCity",
        type: "another",
        address: "1058 Nguyễn Văn Linh, Tân Phong, Quận 7",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7295,
        lng: 106.7075,
        temp: "31°C",
        weatherIcon: "fa-store",
        img: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=500",
        desc: "Trung tâm thương mại tích hợp công viên ngoài trời trên tầng thượng, điểm đến lý tưởng cho gia đình."
    },
    // --- TIẾP THEO: NHÓM ROOFTOP, BIỂU TƯỢNG VÀ TU VIỆN ---
    {
        id: 114,
        name: "Social Club Rooftop",
        type: "nightlife",
        address: "Tầng 24, Hotel des Arts Saigon, 76-78 Nguyễn Thị Minh Khai, Quận 3",
        price: "200.000đ - 500.000đ",
        status: "Mở cửa tối",
        isOpen: true,
        lat: 10.7815,
        lng: 106.6965,
        temp: "28°C",
        weatherIcon: "fa-glass-martini-alt",
        img: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=500",
        desc: "Bar sân thượng sang trọng với hồ bơi vô cực, tầm nhìn 360 độ bao quát toàn cảnh trung tâm Sài Gòn."
    },
    {
        id: 115,
        name: "Square 39 (Khu cắm trại sân thượng)",
        type: "cafe",
        address: "25A Đường số 3, Bình An, Quận 2 (Thủ Đức)",
        price: "50.000đ - 150.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7912,
        lng: 106.7325,
        temp: "30°C",
        weatherIcon: "fa-campground",
        img: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=500",
        desc: "Quán cafe phong cách camping độc đáo trên sân thượng, mang lại trải nghiệm dã ngoại giữa lòng thành phố."
    },
    {
        id: 116,
        name: "Thảo Cầm Viên Sài Gòn",
        type: "sight",
        address: "2 Nguyễn Bỉnh Khiêm, Bến Nghé, Quận 1",
        price: "60.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7875,
        lng: 106.7051,
        temp: "32°C",
        weatherIcon: "fa-hippo",
        img: "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=500",
        desc: "Một trong những vườn bách thảo lâu đời nhất thế giới, lá phổi xanh cực lớn với hàng ngàn loài động thực vật."
    },
    {
        id: 117,
        name: "Tháp Tài chính Bitexco",
        type: "sight",
        address: "2 Hải Triều, Bến Nghé, Quận 1",
        price: "200.000đ (Skydeck)",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7715,
        lng: 106.7045,
        temp: "30°C",
        weatherIcon: "fa-building",
        img: "https://images.unsplash.com/photo-1559592442-6e680bc19660?w=500",
        desc: "Tòa tháp biểu tượng với hình dáng búp sen hé nở, sở hữu đài quan sát ngắm toàn cảnh sông Sài Gòn."
    },
    {
        id: 118,
        name: "The Workshop Coffee",
        type: "cafe",
        address: "27 Ngô Đức Kế, Bến Nghé, Quận 1",
        price: "60.000đ - 150.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7738,
        lng: 106.7040,
        temp: "31°C",
        weatherIcon: "fa-coffee",
        img: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500",
        desc: "Quán cafe Specialty đầu tiên tại Sài Gòn nằm trong một chung cư cũ với không gian công nghiệp hiện đại."
    },
    {
        id: 119,
        name: "Thiso Mall Sala",
        type: "another",
        address: "10 Mai Chí Thọ, Thủ Thiêm, TP. Thủ Đức",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7725,
        lng: 106.7235,
        temp: "31°C",
        weatherIcon: "fa-shopping-bag",
        img: "https://images.unsplash.com/photo-1567449303078-57ad995bd301?w=500",
        desc: "Trung tâm thương mại mới và hiện đại bậc nhất khu đô thị Sala với kiến trúc sang trọng."
    },
    {
        id: 120,
        name: "Trụ sở UBND Thành phố Hồ Chí Minh",
        type: "sight",
        address: "86 Lê Thánh Tôn, Bến Nghé, Quận 1",
        price: "Tham quan bên ngoài",
        status: "Đẹp nhất buổi tối",
        isOpen: true,
        lat: 10.7760,
        lng: 106.7015,
        temp: "30°C",
        weatherIcon: "fa-university",
        img: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=500",
        desc: "Tòa nhà cổ mang phong cách kiến trúc thời Phục hưng Pháp, là điểm check-in di sản quan trọng nhất."
    },
    {
        id: 121,
        name: "Tu viện Khánh An",
        type: "sight",
        address: "1055/3D Võ Thị Thừa, Quận 12",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8805,
        lng: 106.6742,
        temp: "31°C",
        weatherIcon: "fa-torii-gate",
        img: "https://images.unsplash.com/photo-1528127269322-539801943592?w=500",
        desc: "Ngôi chùa được ví như 'Nhật Bản thu nhỏ' với kiến trúc đậm chất xứ sở Phù Tang và không gian thanh tịnh."
    },
    {
        id: 122,
        name: "Tu viện Quảng Hương Già Lam",
        type: "sight",
        address: "498/11 Lê Quang Định, Phường 1, Gò Vấp",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.8195,
        lng: 106.6905,
        temp: "31°C",
        weatherIcon: "fa-place-of-worship",
        img: "https://images.unsplash.com/photo-1621252179027-94459d278660?w=500",
        desc: "Ngôi cổ tự có không gian tĩnh lặng, kiến trúc kết hợp hài hòa giữa nét truyền thống Việt Nam và Ấn Độ."
    },
    {
        id: 123,
        name: "Tượng đài Bác Hồ (Nguyễn Huệ)",
        type: "sight",
        address: "Phố đi bộ Nguyễn Huệ, Quận 1",
        price: "Miễn phí",
        status: "Mở cửa 24/7",
        isOpen: true,
        lat: 10.7758,
        lng: 106.7018,
        temp: "30°C",
        weatherIcon: "fa-user-tie",
        img: "https://images.unsplash.com/photo-1555930058-2976696b010b?w=500",
        desc: "Tượng đài Chủ tịch Hồ Chí Minh uy nghi hướng về sông Sài Gòn, trung tâm của phố đi bộ Nguyễn Huệ."
    },
    {
        id: 124,
        name: "Tượng đài Trần Hưng Đạo",
        type: "sight",
        address: "Công trường Mê Linh, Quận 1",
        price: "Miễn phí",
        status: "Mở cửa 24/7",
        isOpen: true,
        lat: 10.7745,
        lng: 106.7062,
        temp: "30°C",
        weatherIcon: "fa-shield-alt",
        img: "https://images.unsplash.com/photo-1589519160158-1d2a33ec437e?w=500",
        desc: "Tượng đài vị anh hùng dân tộc sừng sững bên bến Bạch Đằng, biểu tượng của ý chí bảo vệ tổ quốc."
    },
    // --- TIẾP THEO: NHÓM TRUNG TÂM THƯƠNG MẠI, CHÙA VÀ LOUNGE CUỐI DANH SÁCH ---
    {
        id: 125,
        name: "Vạn Hạnh Mall",
        type: "another",
        address: "11 Sư Vạn Hạnh, Phường 12, Quận 10",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7712,
        lng: 106.6698,
        temp: "31°C",
        weatherIcon: "fa-shopping-bag",
        img: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=500",
        desc: "Trung tâm thương mại lớn nhất Quận 10 với kiến trúc biểu tượng xây dựng từ những khối màu sắc rực rỡ."
    },
    {
        id: 126,
        name: "Việt Nam Quốc Tự",
        type: "sight",
        address: "244 Ba Tháng Hai, Phường 12, Quận 10",
        price: "Miễn phí",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7748,
        lng: 106.6735,
        temp: "31°C",
        weatherIcon: "fa-place-of-worship",
        img: "https://images.unsplash.com/photo-1528127269322-539801943592?w=500",
        desc: "Ngôi chùa có bảo tháp 13 tầng cao nhất Việt Nam, biểu tượng cho sự thống nhất của Phật giáo Việt Nam."
    },
    {
        id: 127,
        name: "Vincom Centre Đồng Khởi",
        type: "another",
        address: "72 Lê Thánh Tôn, Bến Nghé, Quận 1",
        price: "Miễn phí vào cổng",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7778,
        lng: 106.7015,
        temp: "32°C",
        weatherIcon: "fa-store",
        img: "https://images.unsplash.com/photo-1567449303078-57ad995bd301?w=500",
        desc: "Tòa nhà xanh hiện đại bậc nhất, nơi tập trung các thương hiệu thời trang quốc tế và khu ẩm thực sầm uất."
    },
    {
        id: 128,
        name: "Waterbiz Coffee",
        type: "cafe",
        address: "Ga tàu cao tốc Bạch Đằng, Quận 1",
        price: "50.000đ - 100.000đ",
        status: "Mở cửa",
        isOpen: true,
        lat: 10.7735,
        lng: 106.7068,
        temp: "30°C",
        weatherIcon: "fa-ship",
        img: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=500",
        desc: "Quán cafe view sông Sài Gòn trực diện tại bến tàu, điểm ngắm hoàng hôn và tàu bus sông đẹp nhất."
    },
    {
        id: 129,
        name: "Zion Sky Lounge & Dining",
        type: "nightlife",
        address: "87A Hàm Nghi, Nguyễn Thái Bình, Quận 1",
        price: "200.000đ - 1.000.000đ",
        status: "Mở cửa tối",
        isOpen: true,
        lat: 10.7705,
        lng: 106.7025,
        temp: "28°C",
        weatherIcon: "fa-cocktail",
        img: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=500",
        desc: "Tổ hợp giải trí trên cao với không gian âm nhạc sôi động và tầm nhìn triệu đô hướng về Bitexco."
    }
];